-- Atividades do guia do GitBook (favelaware.gitbook.io/favelaware) como atividades de
-- verdade nas turmas da Edição 4 (2027): o aluno lê a atividade no GitBook
-- (link_enunciado) e entrega no portal.
-- - 144 atividades em cada turma ("Turma 1" e "Turma 2"), sem prazo: a edição ainda
--   não tem datas; o professor define o prazo de cada uma depois.
-- - Enunciado = a descrição curta do GitBook.
-- - Sai da aba Materiais o link de cada atividade que a 20261001125000 colocou lá
--   (continua só o "Guia da trilha no GitBook"). Só apaga o que casa com url, título
--   e ordem daquela migration: material que a equipe cadastrou à mão fica.
-- Pode rodar mais de uma vez: atividade que a turma já tem (mesmo link) não entra de novo.
-- Se as duas turmas da Edição 4 não existirem com esses nomes, não faz nada (só avisa):
-- os links não saem da aba Materiais sem as atividades que os substituem.
-- Trilha que não existir com o nome esperado fica de fora, com aviso.

create temporary table atividades_do_gitbook (trilha text, titulo text, enunciado text, url text, ordem integer);

insert into atividades_do_gitbook (trilha, titulo, enunciado, url, ordem) values
  ('Carreira Tech', 'Atividade 1 - Profissões da área de TI', 'Conheça de perto três profissões de TI e escolha a que mais combina com você.', 'https://favelaware.gitbook.io/favelaware/1-carreira-tech/atividades/atividade-1-profissoes-da-area-de-ti', 1001),
  ('Carreira Tech', 'Atividade 2 - Cursos e caminhos de formação', 'Compare os cursos superiores de TI e monte o seu caminho de estudos.', 'https://favelaware.gitbook.io/favelaware/1-carreira-tech/atividades/atividade-2-cursos-e-caminhos-de-formacao', 1002),
  ('Carreira Tech', 'Atividade 3 - Meu primeiro currículo', 'Monte um currículo de uma página para a área de tecnologia.', 'https://favelaware.gitbook.io/favelaware/1-carreira-tech/atividades/atividade-3-meu-primeiro-curriculo', 1003),
  ('Carreira Tech', 'Atividade 4 - Apresentação pessoal (pitch)', 'Prepare uma apresentação de até 1 minuto sobre você.', 'https://favelaware.gitbook.io/favelaware/1-carreira-tech/atividades/atividade-4-apresentacao-pessoal-pitch', 1004),
  ('Inclusão: Mundo Digital', 'Atividade 1 - Dispositivos de entrada e saída', 'Quiz, perguntas e quebra-cabeças para fixar periféricos de entrada, de saída e de entrada e saída.', 'https://favelaware.gitbook.io/favelaware/2-inclusao-digital/atividades/atividade-1-dispositivos-de-entrada-e-saida', 1001),
  ('Inclusão: Mundo Digital', 'Atividade 2 - Hardware e software', 'Mostre que domina hardware e software: conceitos, componentes, atualizações e a montagem de um computador básico.', 'https://favelaware.gitbook.io/favelaware/2-inclusao-digital/atividades/atividade-2-hardware-e-software', 1002),
  ('Inclusão: Mundo Digital', 'Atividade 3 - Explorando o computador', 'Pratique o uso da área de trabalho, pastas, arquivos e atalhos.', 'https://favelaware.gitbook.io/favelaware/2-inclusao-digital/atividades/atividade-3-explorando-o-computador', 1003),
  ('Inclusão: Mundo Digital', 'Atividade 4 - Tipos de software e sistemas operacionais', 'Classifique os programas que você usa e entenda o papel do sistema operacional.', 'https://favelaware.gitbook.io/favelaware/2-inclusao-digital/atividades/atividade-4-tipos-de-software-e-sistemas-operacionais', 1004),
  ('Mídias Digitais', 'Atividade 1 - E-mail profissional', 'Crie um e-mail profissional e envie sua primeira mensagem formal.', 'https://favelaware.gitbook.io/favelaware/3-midias-digitais/atividades/atividade-1-e-mail-profissional', 1001),
  ('Mídias Digitais', 'Atividade 2 - Organizando arquivos na nuvem (Google Drive)', 'Organize pastas no Google Drive e compartilhe com permissão só de leitura.', 'https://favelaware.gitbook.io/favelaware/3-midias-digitais/atividades/atividade-2-organizando-arquivos-na-nuvem-google-drive', 1002),
  ('Mídias Digitais', 'Atividade 3 - Documento bem formatado (Google Docs)', 'Crie um documento com título, tópicos, imagem e tabela.', 'https://favelaware.gitbook.io/favelaware/3-midias-digitais/atividades/atividade-3-documento-bem-formatado-google-docs', 1003),
  ('Mídias Digitais', 'Atividade 4 - Pesquisa e fontes confiáveis', 'Pesquise um tema e avalie se as fontes são confiáveis.', 'https://favelaware.gitbook.io/favelaware/3-midias-digitais/atividades/atividade-4-pesquisa-e-fontes-confiaveis', 1004),
  ('Pensamento Lógico', 'Atividade 1 - Pensamento lógico no dia a dia', 'Coloque a mão na massa e use o pensamento lógico em situações do dia a dia.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-1-pensamento-logico-no-dia-a-dia', 1001),
  ('Pensamento Lógico', 'Atividade 2 - Jogos de lógica', 'Jogue os jogos de lógica separados para a turma e veja o pensamento lógico em ação.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-2-jogos-de-logica', 1002),
  ('Pensamento Lógico', 'Atividade 3 - Quebra-cabeça em dupla', 'Monte um quebra-cabeça em dupla e treine o pensamento lógico com trabalho em equipe.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-3-quebra-cabeca-em-dupla', 1003),
  ('Pensamento Lógico', 'Atividade 4 - Questões de lógica', 'Resolva questões de lógica de vestibulares e concursos, da prática aos desafios.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-4-questoes-de-logica', 1004),
  ('Pensamento Lógico', 'Atividade 5 - Questões de lógica: aquecimento', 'Aqueça o raciocínio com sequências, pegadinhas e problemas do dia a dia, até chegar em questões de concurso.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-5-questoes-de-logica-aquecimento', 1005),
  ('Pensamento Lógico', 'Atividade 6 - Dinâmicas em grupo', 'Participe de três dinâmicas em grupo feitas em sala e conte o que aprendeu com elas.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-6-dinamicas-em-grupo', 1006),
  ('Pensamento Lógico', 'Atividade 7 - Raciocínio lógico e ilógico', 'Identifique decisões lógicas no dia a dia e encontre falhas de raciocínio.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-7-raciocinio-logico-e-ilogico', 1007),
  ('Pensamento Lógico', 'Atividade 8 - Compute-It', 'Jogue Compute-It e pense como um computador lendo código.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-8-compute-it', 1008),
  ('Pensamento Lógico', 'Atividade 9 - Little Dot Adventure', 'Jogue Little Dot Adventure e descubra conceitos básicos de programação.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-9-little-dot-adventure', 1009),
  ('Pensamento Lógico', 'Atividade 10 - Primeiros passos com Hedy', 'Faça os primeiros níveis do Hedy e corrija um código com erro.', 'https://favelaware.gitbook.io/favelaware/4-pensamento-logico/atividades/atividade-10-primeiros-passos-com-hedy', 1010),
  ('Git e GitHub', 'Atividade 1 - História do Git e controle de versão', 'Responda com suas palavras perguntas sobre a história do Git, o controle de versão e a diferença entre Git e GitHub.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-1-historia-do-git-e-controle-de-versao', 1001),
  ('Git e GitHub', 'Atividade 2 - Instalando e configurando o Git', 'Instale o Git, confira a versão e deixe seu nome e e-mail configurados no Git Bash.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-2-instalando-e-configurando-o-git', 1002),
  ('Git e GitHub', 'Atividade 3 - Comandos básicos do Git', 'Pratique init, status, add, commit, log, clone e checkout criando e controlando projetos simples com o Git.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-3-comandos-basicos-do-git', 1003),
  ('Git e GitHub', 'Atividade 4 - Branches e merges', 'Crie branches, faça merge, provoque e resolva um conflito e limpe as branches de um site pessoal.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-4-branches-e-merges', 1004),
  ('Git e GitHub', 'Atividade 5 - Workflows do Git', 'Aplique na prática o workflow local, o Feature Branch e o Git Flow, com feature, release e hotfix.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-5-workflows-do-git', 1005),
  ('Git e GitHub', 'Atividade 6 - Pull Request', 'Simule o fluxo de Pull Request de um time: branch, push, PR, revisão, merge e limpeza da branch.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-6-pull-request', 1006),
  ('Git e GitHub', 'Atividade 7 - README do perfil do GitHub', 'Crie o README que aparece na página do seu perfil do GitHub e deixe seu perfil com cara de portfólio.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-7-readme-do-perfil-do-github', 1007),
  ('Git e GitHub', 'Atividade 8 - README de um projeto', 'Escreva um README completo para um dos seus repositórios, com o que faz, tecnologias, como rodar e contato.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-8-readme-de-um-projeto', 1008),
  ('Git e GitHub', 'Atividade 9 - Lista de exercícios de Git e GitHub', 'Lista em 5 níveis que revisa a trilha toda: repositório, branches, conflito, Pull Request, colaboração e hotfix.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-9-lista-de-exercicios-de-git-e-github', 1009),
  ('Git e GitHub', 'Atividade 10 - Projeto final: Diário de Versionamento em Equipe', 'Em grupo, crie um repositório colaborativo usando branches, commits, Pull Requests e revisões, como um time de verdade.', 'https://favelaware.gitbook.io/favelaware/5-git-e-github/atividades/atividade-10-projeto-final-diario-de-versionamento-em-equipe', 1010),
  ('HTML', 'Atividade 1 - Etiquetando o panfleto do baile', 'Olhe um panfleto de evento com olhos de dev: diga que tag marca cada parte e se cada recurso é trabalho do HTML, do CSS ou do JavaScript.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-1-etiquetando-o-panfleto-do-baile', 1001),
  ('HTML', 'Atividade 2 - Esqueleto da página da Associação de Moradores', 'Decida o que vai no head e no body e monte o esqueleto semântico da página da associação de moradores, com comentários e indentação.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-2-esqueleto-da-pagina-da-associacao-de-moradores', 1002),
  ('HTML', 'Atividade 3 - Cabeçalhos, parágrafos e formatação', 'Revise cabeçalhos, parágrafos e tags de formatação com questões objetivas e dois exercícios práticos de código.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-3-cabecalhos-paragrafos-e-formatacao', 1003),
  ('HTML', 'Atividade 4 - Promoção do Mercadinho do Seu Zé', 'Monte o encarte de ofertas de um mercadinho usando hierarquia de cabeçalhos e as tags del, ins, mark e small.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-4-promocao-do-mercadinho-do-seu-ze', 1004),
  ('HTML', 'Atividade 5 - Organizando o churrasco da laje', 'Preveja como o navegador mostra listas e depois organize um churrasco com listas ordenadas, não ordenadas, type e listas aninhadas.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-5-organizando-o-churrasco-da-laje', 1005),
  ('HTML', 'Atividade 6 - Tabelas da Copa da Quebrada e do cursinho', 'Preveja como uma tabela com colspan e rowspan aparece e depois monte a classificação de um campeonato e a grade de horários de um cursinho.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-6-tabelas-da-copa-da-quebrada-e-do-cursinho', 1006),
  ('HTML', 'Atividade 7 - Imagens', 'Revise a tag img, os atributos src, alt, width e height e os caminhos de imagem com questões objetivas e práticas.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-7-imagens', 1007),
  ('HTML', 'Atividade 8 - Revisão de imagens: atributos e o alt', 'Aprofunde o uso de imagens: atributos certos, o que acontece com src errado e o papel do alt em acessibilidade e SEO.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-8-revisao-de-imagens-atributos-e-o-alt', 1008),
  ('HTML', 'Atividade 9 - Conserte a página do Vila Unida FC', 'Caça ao bug: encontre e corrija os 8 erros de HTML na página do time de várzea, envolvendo tags, listas, imagens e links.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-9-conserte-a-pagina-do-vila-unida-fc', 1009),
  ('HTML', 'Atividade 10 - Ficha de inscrição da Copa da Quebrada', 'Monte a ficha de inscrição de um campeonato com texto, e-mail, senha, radio, checkbox, lista suspensa, caixa de texto e links.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-10-ficha-de-inscricao-da-copa-da-quebrada', 1010),
  ('HTML', 'Atividade 11 - Recriando a página do Brechó da Dona Cida', 'Leia a descrição de um print e reproduza a página do brechó com títulos, formatação, listas, imagem, links e um formulário de reserva.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-11-recriando-a-pagina-do-brecho-da-dona-cida', 1011),
  ('HTML', 'Atividade 12 - Desafio final: Minha Página Pessoal', 'Crie uma página pessoal completa em HTML puro, com títulos, formatação, listas, imagem, links e formulário de contato.', 'https://favelaware.gitbook.io/favelaware/6-html/atividades/atividade-12-desafio-final-minha-pagina-pessoal', 1012),
  ('CSS', 'Atividade 1 - Conserte o CSS da barbearia', 'O site da barbearia do bairro está sem estilo por causa de erros de sintaxe. Encontre e corrija os 6 erros do CSS.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-1-conserte-o-css-da-barbearia', 1001),
  ('CSS', 'Atividade 2 - Cardápio da pastelaria em três versões', 'Faça o mesmo cardápio de pastel com CSS inline, interno e externo, organize as pastas e descubra na prática qual forma dá menos trabalho.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-2-cardapio-da-pastelaria-em-tres-versoes', 1002),
  ('CSS', 'Atividade 3 - Cartaz do sarau da quebrada', 'Monte o cartaz digital do sarau da comunidade usando fonte, tamanho, alinhamento, largura, margin e padding.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-3-cartaz-do-sarau-da-quebrada', 1003),
  ('CSS', 'Atividade 4 - Inscrição da Copa da Quebrada sem mexer no HTML', 'Estilize a página de inscrição do campeonato usando tag, classe, id, universal e seletores de atributo, sem alterar uma linha do HTML.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-4-inscricao-da-copa-da-quebrada-sem-mexer-no-html', 1004),
  ('CSS', 'Atividade 5 - Qual regra vence? Briga de seletores', 'Duas regras mandam cores diferentes para o mesmo elemento. Preveja qual vence em 8 casos, teste no navegador e explique a cascata.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-5-qual-regra-vence-briga-de-seletores', 1005),
  ('CSS', 'Atividade 6 - Uniforme do time da várzea', 'Crie a página do time da várzea escrevendo a mesma cor em HEX, RGB e HSL, usando transparência e botões com currentcolor.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-6-uniforme-do-time-da-varzea', 1006),
  ('CSS', 'Atividade 7 - Lista de compras do mercadinho interativa', 'Deixe a lista de compras do Mercadinho do Tião viva: listras, destaques, formulário que reage e enfeites sem mexer no HTML.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-7-lista-de-compras-do-mercadinho-interativa', 1007),
  ('CSS', 'Atividade 8 - Detetive de combinadores e CSS Diner', 'Descubra quais parágrafos cada combinador pega no quadro de horários do ônibus e depois treine seletores jogando o CSS Diner.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-8-detetive-de-combinadores-e-css-diner', 1008),
  ('CSS', 'Atividade 9 - Vitrine do brechó: a caixa que não cabe', 'Calcule no papel por que as peças do brechó não cabem na vitrine, conserte o layout e adicione selo, cabeçalho grudado e peça esgotada.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-9-vitrine-do-brecho-a-caixa-que-nao-cabe', 1009),
  ('CSS', 'Atividade 10 - Botões animados da rádio comunitária', 'Dê vida aos cards da rádio comunitária com scale, rotate, translate e skew, e descubra na prática por que a ordem das transformações importa.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-10-botoes-animados-da-radio-comunitaria', 1010),
  ('CSS', 'Atividade 11 - Cartão de perfil do artista da quebrada', 'Monte cartões de perfil de artistas do bairro com Flexbox: foto, nome, números, botões e cartões que quebram linha.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-11-cartao-de-perfil-do-artista-da-quebrada', 1011),
  ('CSS', 'Atividade 12 - Preveja o Flexbox e monte o menu da linha de ônibus', 'Desenhe o resultado de 6 códigos Flexbox antes de rodar, compare com o navegador e depois construa um menu que vira coluna no celular.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-12-preveja-o-flexbox-e-monte-o-menu-da-linha-de-onibus', 1012),
  ('CSS', 'Atividade 13 - Sapos e cenouras: Flexbox Froggy e Grid Garden', 'Jogue Flexbox Froggy e Grid Garden, dois jogos que ensinam layout brincando, e registre as fases e as propriedades novas que descobriu.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-13-sapos-e-cenouras-flexbox-froggy-e-grid-garden', 1013),
  ('CSS', 'Atividade 14 - Cardápio do trailer que se adapta à tela', 'Descubra por que o cardápio do trailer fica errado no celular, conserte as media queries e faça tudo crescer junto usando rem e em.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-14-cardapio-do-trailer-que-se-adapta-a-tela', 1014),
  ('CSS', 'Atividade 15 - Site da associação de moradores responsivo', 'Projeto final: construa a página da associação de moradores com Grid, Flexbox e tudo da trilha, funcionando no computador e no celular.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-15-site-da-associacao-de-moradores-responsivo', 1015),
  ('CSS', 'Atividade 16 - Site da associação no ar', 'Publique o site da associação de moradores no GitHub Pages ou na Vercel e entregue o link do site funcionando no ar.', 'https://favelaware.gitbook.io/favelaware/7-css/atividades/atividade-16-site-da-associacao-no-ar', 1016),
  ('Lógica de Programação', 'Atividade 1 - Tabela-verdade da quebrada', 'Monte tabelas-verdade com E, OU e NÃO para situações do dia a dia e confira seu raciocínio com fórmulas do Excel.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-1-tabela-verdade-da-quebrada', 1001),
  ('Lógica de Programação', 'Atividade 2 - Algoritmo para pegar o ônibus certo', 'Organize passos embaralhados e escreva um algoritmo do dia a dia para sair de casa e pegar o ônibus certo, sem deixar brecha.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-2-algoritmo-para-pegar-o-onibus-certo', 1002),
  ('Lógica de Programação', 'Atividade 3 - Rachando a conta do churrasco', 'Use os seis passos de construção de um algoritmo para dividir a conta do churrasco da laje de um jeito justo.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-3-rachando-a-conta-do-churrasco', 1003),
  ('Lógica de Programação', 'Atividade 4 - Variáveis e operadores do time de várzea', 'Monte o cadastro de um jogador do time da quebrada escolhendo tipos, variáveis e constantes, e calcule expressões com operadores.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-4-variaveis-e-operadores-do-time-de-varzea', 1004),
  ('Lógica de Programação', 'Atividade 5 - Escolhendo a estrutura certa', 'Decida qual estrutura de controle, de dados ou função resolve cada situação do dia a dia, e justifique a escolha.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-5-escolhendo-a-estrutura-certa', 1005),
  ('Lógica de Programação', 'Atividade 6 - O que este Portugol imprime?', 'Leia cinco programas curtos em Portugol, preveja exatamente o que aparece na tela e explique o porquê antes de executar.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-6-o-que-este-portugol-imprime', 1006),
  ('Lógica de Programação', 'Atividade 7 - Condições em Portugol', 'Escreva seus primeiros programas em Portugol usando se, então e senão para tomar decisões com números, notas, senha e idade.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-7-condicoes-em-portugol', 1007),
  ('Lógica de Programação', 'Atividade 8 - Operadores lógicos em Portugol', 'Combine condições com e, ou e não em Portugol para testar intervalos, sinais de números e valores lógicos.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-8-operadores-logicos-em-portugol', 1008),
  ('Lógica de Programação', 'Atividade 9 - Catraca inteligente: tarifa do ônibus', 'Programe a catraca que calcula a tarifa do ônibus com linha, gratuidade por idade, integração e meia de estudante.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-9-catraca-inteligente-tarifa-do-onibus', 1009),
  ('Lógica de Programação', 'Atividade 10 - Laços de repetição em Portugol', 'Use laços em Portugol para contar, somar, fazer tabuada, calcular médias e achar o maior e o menor de uma lista.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-10-lacos-de-repeticao-em-portugol', 1010),
  ('Lógica de Programação', 'Atividade 11 - Vetores e matrizes: notas da turma e tabela do campeonato', 'Use vetores para analisar as notas da turma e uma matriz para montar a tabela do campeonato de várzea em Portugol.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-11-vetores-e-matrizes-notas-da-turma-e-tabela-do-campeonato', 1011),
  ('Lógica de Programação', 'Atividade 12 - Conta de luz em partes: funções em Portugol', 'Quebre o cálculo da conta de luz em funções com parâmetros e retorno em Portugol, deixando o inicio curto e fácil de ler.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-12-conta-de-luz-em-partes-funcoes-em-portugol', 1012),
  ('Lógica de Programação', 'Atividade 13 - Teste de mesa: o cofrinho e a sequência misteriosa', 'Acompanhe as variáveis de dois programas com laço, linha a linha, numa planilha de teste de mesa, sem executar antes.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-13-teste-de-mesa-o-cofrinho-e-a-sequencia-misteriosa', 1013),
  ('Lógica de Programação', 'Atividade 14 - Caça aos bugs de lógica', 'Cinco programas em Portugol rodam sem erro de sintaxe, mas dão a resposta errada. Encontre o erro de lógica e conserte.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-14-caca-aos-bugs-de-logica', 1014),
  ('Lógica de Programação', 'Atividade 15 - Troco com o menor número de peças', 'Resolva no papel, em passos, como dar troco com o menor número de notas e moedas, e só depois programe a solução em Portugol.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-15-troco-com-o-menor-numero-de-pecas', 1015),
  ('Lógica de Programação', 'Atividade 16 - Fluxograma do atendimento no posto de saúde', 'Transforme o relato de um atendimento no posto de saúde do bairro num fluxograma com decisões, repetição e símbolos corretos.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-16-fluxograma-do-atendimento-no-posto-de-saude', 1016),
  ('Lógica de Programação', 'Atividade 17 - Fluxograma', 'Desenhe no draw.io os fluxogramas de 16 problemas: notas, lanchonete, salários, crescimento, pet shop, faixa etária e temperatura.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-17-fluxograma', 1017),
  ('Lógica de Programação', 'Atividade 18 - Desafio final: o caixa do mercadinho', 'Planeje com fluxograma e programe em Portugol o caixa do mercadinho: produtos, quantidades, desconto, pagamento e troco.', 'https://favelaware.gitbook.io/favelaware/8-logica-de-programacao/atividades/atividade-18-desafio-final-o-caixa-do-mercadinho', 1018),
  ('JavaScript', 'Atividade 1 - Variáveis, tipos e boas práticas', '20 exercícios de fixação sobre variáveis, tipos de dados, concatenação, referência e comentários, do básico ao raciocínio.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-1-variaveis-tipos-e-boas-praticas', 1001),
  ('JavaScript', 'Atividade 2 - O que este código imprime?', 'Adivinhe o que 9 trechos de código mostram no console antes de rodar e explique o porquê: tipos, coerção, escopo e referência.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-2-o-que-este-codigo-imprime', 1002),
  ('JavaScript', 'Atividade 3 - Praticando operadores', '10 exercícios rápidos com operadores aritméticos, de incremento, relacionais, lógicos, ternário e precedência.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-3-praticando-operadores', 1003),
  ('JavaScript', 'Atividade 4 - Caça aos bugs dos operadores', '8 trechos de código com um bug escondido cada: ache o erro de operador, corrija e explique o que estava acontecendo.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-4-caca-aos-bugs-dos-operadores', 1004),
  ('JavaScript', 'Atividade 5 - Estruturas condicionais', '20 exercícios de if, else if, else, switch, ternário e operadores lógicos com situações do dia a dia.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-5-estruturas-condicionais', 1005),
  ('JavaScript', 'Atividade 6 - Calculadora da tarifa do busão', 'Monte a calculadora da passagem de ônibus com meia, gratuidade, integração e domingo de tarifa zero usando if, switch e &&.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-6-calculadora-da-tarifa-do-busao', 1006),
  ('JavaScript', 'Atividade 7 - Arrays', '20 exercícios com arrays: criar, acessar, adicionar e remover itens, map, filter, reduce, sort, find, split, join e flat.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-7-arrays', 1007),
  ('JavaScript', 'Atividade 8 - Carrinho do mercadinho com desconto', 'Monte a nota do pedido do Mercadinho da Vila com array de objetos, forEach e reduce, aplicando desconto, cupom e taxa de entrega.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-8-carrinho-do-mercadinho-com-desconto', 1008),
  ('JavaScript', 'Atividade 9 - Teste de mesa: a vaquinha do churrasco', 'Siga um laço for com continue e break volta por volta numa planilha, anotando cada variável, antes de rodar o código.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-9-teste-de-mesa-a-vaquinha-do-churrasco', 1009),
  ('JavaScript', 'Atividade 10 - Estruturas de repetição', '20 exercícios de for, while, do...while, for...of, for...in, break, continue e loops aninhados, do básico ao avançado.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-10-estruturas-de-repeticao', 1010),
  ('JavaScript', 'Atividade 11 - Boletim da turma: média e situação', 'Calcule média, frequência e situação de cada aluno da turma com loops aninhados e monte o resumo da sala.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-11-boletim-da-turma-media-e-situacao', 1011),
  ('JavaScript', 'Atividade 12 - Relatório de vendas da feira', 'Monte o relatório de vendas da feira do fim de semana usando só map, filter, reduce, find e sort, sem escrever nenhum for.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-12-relatorio-de-vendas-da-feira', 1012),
  ('JavaScript', 'Atividade 13 - Complete as funções da conta de luz', 'Complete as funções que calculam a conta de luz: consumo, faixa de tarifa, bandeira e tarifa social, com testes prontos.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-13-complete-as-funcoes-da-conta-de-luz', 1013),
  ('JavaScript', 'Atividade 14 - Cadastro seguro: senha forte, nome e CPF', 'Escreva funções que mexem com texto: validar senha forte, arrumar nome digitado de qualquer jeito e formatar e esconder CPF fictício.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-14-cadastro-seguro-senha-forte-nome-e-cpf', 1014),
  ('JavaScript', 'Atividade 15 - Refatorando o delivery da lanchonete', 'Transforme um código repetido de cálculo de frete em funções com parâmetros, retorno e valor padrão, sem mudar o resultado.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-15-refatorando-o-delivery-da-lanchonete', 1015),
  ('JavaScript', 'Atividade 16 - Funções', '30 questões sobre funções: parâmetros, return, arrow functions, escopo, hoisting, IIFE, rest, callbacks, closures e recursão.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-16-funcoes', 1016),
  ('JavaScript', 'Atividade 17 - Tabela do campeonato da quebrada', 'Monte a tabela de classificação do torneio de futebol do bairro com funções, callbacks e sort, com critério de desempate.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-17-tabela-do-campeonato-da-quebrada', 1017),
  ('JavaScript', 'Atividade 18 - Controle de estoque do mercadinho', 'Crie as classes Produto e Estoque do mercadinho, com quantidade protegida, vendas, reposição e valor total do estoque.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-18-controle-de-estoque-do-mercadinho', 1018),
  ('JavaScript', 'Atividade 19 - Classes e objetos', '30 exercícios de objetos literais, JSON, classes, protótipos, herança, pilares da POO e desafios finais com carrinho e API.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-19-classes-e-objetos', 1019),
  ('JavaScript', 'Atividade 20 - Agenda de contatos da quebrada', 'Mini projeto: agenda de contatos com classes, campo privado, busca, validação, favoritos e exportação e importação em JSON.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-20-agenda-de-contatos-da-quebrada', 1020),
  ('JavaScript', 'Atividade 21 - Caixa eletrônico do Banco da Quebrada', 'Mini projeto: simule um caixa eletrônico com senha e bloqueio, saque em notas, limite diário, extrato e menu interativo.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-21-caixa-eletronico-do-banco-da-quebrada', 1021),
  ('JavaScript', 'Atividade 22 - Jogo de adivinhação com recorde', 'Projeto final: jogo de adivinhação com níveis, validação dos chutes, dica de quente ou frio e recorde, usando classes e loops.', 'https://favelaware.gitbook.io/favelaware/9-javascript/atividades/atividade-22-jogo-de-adivinhacao-com-recorde', 1022),
  ('JavaScript para Web', 'Atividade 1 - Desenhando a árvore do DOM', 'Transforme o HTML do cardápio de uma lanchonete em árvore do DOM e descubra, no console, o que o navegador enxerga.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-1-desenhando-a-arvore-do-dom', 1001),
  ('JavaScript para Web', 'Atividade 2 - Primeiro script no DOM: mensagem atualizada', 'Seu primeiro script mexendo na página: encontre um elemento pelo id, troque o texto dele e descubra no console quem é o primeiro filho do body.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-2-primeiro-script-no-dom-mensagem-atualizada', 1002),
  ('JavaScript para Web', 'Atividade 3 - Selecionar e alterar elementos: a escalação do time', 'Use id, classe, seletor CSS, pai, filhos e irmãos para atualizar a escalação do time de várzea antes do jogo de domingo.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-3-selecionar-e-alterar-elementos-a-escalacao-do-time', 1003),
  ('JavaScript para Web', 'Atividade 4 - Botão que muda o título', 'Faça um botão mudar o texto e a cor do título com um clique, e depois crie outro botão que desfaz a mudança.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-4-botao-que-muda-o-titulo', 1004),
  ('JavaScript para Web', 'Atividade 5 - Mural de avisos: criar e remover itens de uma lista', 'Monte o mural de avisos da associação de moradores: crie avisos novos com createElement e tire os antigos com remove().', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-5-mural-de-avisos-criar-e-remover-itens-de-uma-lista', 1005),
  ('JavaScript para Web', 'Atividade 6 - Tema claro e escuro na rádio comunitária', 'Encontre e corrija os erros de um botão de modo escuro e faça ele alternar entre claro e escuro usando classList.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-6-tema-claro-e-escuro-na-radio-comunitaria', 1006),
  ('JavaScript para Web', 'Atividade 7 - Lotação da van: contador de cliques com limite', 'Crie o contador de passageiros da van da quebrada: sobe e desce com cliques, avisa quando lota e nunca passa do limite.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-7-lotacao-da-van-contador-de-cliques-com-limite', 1007),
  ('JavaScript para Web', 'Atividade 8 - Galeria do sarau com botões próximo e anterior', 'Monte a galeria de fotos do sarau da quebrada: um slide por vez, botões próximo e anterior e contador de posição.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-8-galeria-do-sarau-com-botoes-proximo-e-anterior', 1008),
  ('JavaScript para Web', 'Atividade 9 - Racha da pizza: calculadora de conta dividida', 'Crie a calculadora do racha da pizzaria: lê os campos, soma a gorjeta, divide pela galera e atualiza ao vivo com o evento input.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-9-racha-da-pizza-calculadora-de-conta-dividida', 1009),
  ('JavaScript para Web', 'Atividade 10 - Inscrição no campeonato: validar o formulário antes de enviar', 'Segure o envio do formulário de inscrição do campeonato com preventDefault e mostre o erro de cada campo antes de aceitar.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-10-inscricao-no-campeonato-validar-o-formulario-antes-de-enviar', 1010),
  ('JavaScript para Web', 'Atividade 11 - Guia de serviços da quebrada: filtro de busca', 'Complete o código do guia de serviços do bairro e crie um filtro que busca enquanto a pessoa digita, com categorias e contador.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-11-guia-de-servicos-da-quebrada-filtro-de-busca', 1011),
  ('JavaScript para Web', 'Atividade 12 - JavaScript e DOM na prática', 'Revisão completa da trilha em 31 exercícios: console, seleção, alteração, navegação no DOM, eventos, bubbling e três mini projetos.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-12-javascript-e-dom-na-pratica', 1012),
  ('JavaScript para Web', 'Atividade 13 - Quadro de tarefas do mutirão', 'Crie o quadro de tarefas do mutirão da laje com responsável, contador de pendentes, limpeza das concluídas e delegação de eventos.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-13-quadro-de-tarefas-do-mutirao', 1013),
  ('JavaScript para Web', 'Atividade 14 - Desafio final: jogo da velha da vila', 'Projeto final da trilha: um jogo da velha completo no navegador, com vez de cada jogador, vitória, empate e placar da melhor de 5.', 'https://favelaware.gitbook.io/favelaware/10-javascript-para-web/atividades/atividade-14-desafio-final-jogo-da-velha-da-vila', 1014),
  ('Trabalhando com APIs', 'Atividade 1 - Lendo e montando JSON', 'Leia o JSON das linhas de ônibus da quebrada, ache os erros de um JSON quebrado e monte o cardápio da lanchonete em JSON.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-1-lendo-e-montando-json', 1001),
  ('Trabalhando com APIs', 'Atividade 2 - Qual status a API devolve?', 'Você é a API do app do mercadinho do bairro: para cada situação, escolha o código de status HTTP certo e justifique.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-2-qual-status-a-api-devolve', 1002),
  ('Trabalhando com APIs', 'Atividade 3 - Consumindo uma API (GET) - parte 1', 'Primeiros exercícios de consumo de API com GET e fetch, seguindo o documento da atividade.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-3-consumindo-uma-api-get-parte-1', 1003),
  ('Trabalhando com APIs', 'Atividade 4 - Quando a API falha: erros amigáveis', 'Descubra por que o .catch() não pega um 404, reescreva com async/await e mostre mensagens amigáveis quando a API falha.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-4-quando-a-api-falha-erros-amigaveis', 1004),
  ('Trabalhando com APIs', 'Atividade 5 - Página de frete do mercadinho com ViaCEP', 'Crie uma página HTML que busca o CEP do cliente na ViaCEP, mostra o endereço e calcula o frete do mercadinho pela regra de entrega.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-5-pagina-de-frete-do-mercadinho-com-viacep', 1005),
  ('Trabalhando com APIs', 'Atividade 6 - Consumindo uma API (GET) - parte 2', 'Consuma APIs brasileiras reais com GET: CEP na BrasilAPI e ViaCEP, estados e cidades no IBGE, cotações, tabela FIPE, Câmara e feriados.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-6-consumindo-uma-api-get-parte-2', 1006),
  ('Trabalhando com APIs', 'Atividade 7 - Inserindo dados (POST)', 'Questões e exercícios práticos de POST com fetch: headers, JSON.stringify, tratamento de erro, função reutilizável e formulário HTML.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-7-inserindo-dados-post', 1007),
  ('Trabalhando com APIs', 'Atividade 8 - Método PUT', 'Questões e exercícios de PUT com fetch: substituir usuários, posts, tarefas e álbuns inteiros e criar funções reutilizáveis.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-8-metodo-put', 1008),
  ('Trabalhando com APIs', 'Atividade 9 - Método PATCH', 'Questões e exercícios de PATCH com fetch: atualizar só o nome, o telefone, o e-mail ou a cidade, sem reenviar o recurso inteiro.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-9-metodo-patch', 1009),
  ('Trabalhando com APIs', 'Atividade 10 - Método DELETE', 'Questões e exercícios de DELETE com fetch: conferir o status, tratar recurso inexistente e erro de rede e dar retorno claro ao usuário.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-10-metodo-delete', 1010),
  ('Trabalhando com APIs', 'Atividade 11 - Token no header: 401, 403 e JWT na prática', 'Faça login numa API de teste, envie o token no header, veja o 401 acontecer, abra o JWT por dentro e trate cada erro no código.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-11-token-no-header-401-403-e-jwt-na-pratica', 1011),
  ('Trabalhando com APIs', 'Atividade 12 - Exercícios extras de API', 'Agora que você sabe o básico sobre API, exercite esse conhecimento resolvendo as questões extras do documento.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-12-exercicios-extras-de-api', 1012),
  ('Trabalhando com APIs', 'Atividade 13 - Explorando a API do Rick and Morty no Postman', 'Monte uma coleção no Postman, busque personagens, use filtros, siga os links da resposta e descubra o que a API faz quando algo não existe.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-13-explorando-a-api-do-rick-and-morty-no-postman', 1013),
  ('Trabalhando com APIs', 'Atividade 14 - API do campeonato da quebrada', 'Conserte as rotas mal feitas da API do campeonato e construa ela em Express com rotas REST, versão, JSON padronizado e status certos.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-14-api-do-campeonato-da-quebrada', 1014),
  ('Trabalhando com APIs', 'Atividade 15 - Mini projeto: to-do list com MVC', 'Construa sua primeira API RESTful de tarefas com Express e estrutura MVC, com dados em memória e testes no Postman.', 'https://favelaware.gitbook.io/favelaware/11-apis/atividades/atividade-15-mini-projeto-to-do-list-com-mvc', 1015),
  ('Banco de Dados', 'Atividade 1 - Caça ao tesouro de dados', 'Vire detetive de dados por 24 horas: encontre 10 dados no seu dia a dia, anote de onde vieram e que informação eles geram.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-1-caca-ao-tesouro-de-dados', 1001),
  ('Banco de Dados', 'Atividade 2 - Gaveta ou caixa? Relacional ou não relacional', 'Analise sete projetos da quebrada e decida se cada um pede banco relacional ou não relacional, justificando com o que viu na aula.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-2-gaveta-ou-caixa-relacional-ou-nao-relacional', 1002),
  ('Banco de Dados', 'Atividade 3 - A planilha do Unidos da Laje FC', 'Pegue a planilha bagunçada de um time de várzea, descubra os dados e os tipos de cada coluna e aponte o que o banco teria barrado.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-3-a-planilha-do-unidos-da-laje-fc', 1003),
  ('Banco de Dados', 'Atividade 4 - Biblioteca comunitária: do caderno às tabelas', 'Transforme o caderno de empréstimos da biblioteca comunitária em tabelas ligadas por chave primária e chave estrangeira.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-4-biblioteca-comunitaria-do-caderno-as-tabelas', 1004),
  ('Banco de Dados', 'Atividade 5 - Modelando seu mundo: chaves primária e estrangeira', 'Vire arquiteto(a) de dados: escolha uma ideia sua e desenhe o modelo do banco relacional, com tabelas, tipos, chaves e relacionamentos.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-5-modelando-seu-mundo-chaves-primaria-e-estrangeira', 1005),
  ('Banco de Dados', 'Atividade 6 - Súmula da várzea: SELECT com filtro e ordem', 'Preveja o resultado de consultas SELECT antes de rodar e depois escreva as suas para responder o que o técnico do time quer saber.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-6-sumula-da-varzea-select-com-filtro-e-ordem', 1006),
  ('Banco de Dados', 'Atividade 7 - O caderninho do fiado: INSERT, UPDATE e DELETE com cuidado', 'Atualize o caderninho de fiado do mercadinho prevendo, antes de rodar, quantas linhas cada INSERT, UPDATE e DELETE vai mexer.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-7-o-caderninho-do-fiado-insert-update-e-delete-com-cuidado', 1007),
  ('Banco de Dados', 'Atividade 8 - Missão SQL: o detetive de dados', 'Interrogue o banco de uma agência de heróis com SELECT, INSERT, UPDATE, DELETE e INNER JOIN, do jeito que um detetive faria.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-8-missao-sql-o-detetive-de-dados', 1008),
  ('Banco de Dados', 'Atividade 9 - Quem está com o livro? Desafio de JOIN', 'Responda às perguntas da biblioteca comunitária cruzando três tabelas com INNER JOIN e descubra o erro na consulta de um colega.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-9-quem-esta-com-o-livro-desafio-de-join', 1009),
  ('Banco de Dados', 'Atividade 10 - Definindo as regras do jogo (constraints)', 'Aja como legislador(a) do banco: decida quais constraints as tabelas da agência precisam e justifique as regras das chaves estrangeiras.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-10-definindo-as-regras-do-jogo-constraints', 1010),
  ('Banco de Dados', 'Atividade 11 - Cada um no seu prato: RLS na prática', 'Proteja os pedidos da marmitaria com Row Level Security: cada cliente só vê e mexe nos próprios pedidos, e você prova isso testando.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-11-cada-um-no-seu-prato-rls-na-pratica', 1011),
  ('Banco de Dados', 'Atividade 12 - O cofre da marmitaria: buckets e políticas no Storage', 'Crie um bucket público e um privado no Supabase Storage, suba arquivos e controle quem pode ver, enviar e apagar cada um.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-12-o-cofre-da-marmitaria-buckets-e-politicas-no-storage', 1012),
  ('Banco de Dados', 'Atividade 13 - Tunando o projeto com os superpoderes do Supabase', 'Planeje como Auth, RLS, Storage e Realtime deixariam o seu projeto (ou a agência de heróis) mais completo e seguro.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-13-tunando-o-projeto-com-os-superpoderes-do-supabase', 1013),
  ('Banco de Dados', 'Atividade 14 - Seu primeiro robô de dados', 'Programe sua primeira Database Function no Supabase e teste o robô chamando ele com SELECT.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-14-seu-primeiro-robo-de-dados', 1014),
  ('Banco de Dados', 'Atividade 15 - Projeto final: o banco do Campeonato Interquebradas', 'Monte do zero o banco de um campeonato de várzea: tabelas com chaves e constraints, dados, consultas com JOIN e funções.', 'https://favelaware.gitbook.io/favelaware/12-banco-de-dados/atividades/atividade-15-projeto-final-o-banco-do-campeonato-interquebradas', 1015);

do $$
declare
  v_apagados integer;
  v_criadas integer;
  v_turmas integer;
  v_faltando text;
begin
  select count(*) into v_turmas
  from public.turmas tu
  join public.edicoes e on e.id = tu.edicao_id
  where e.nome = 'Edição 4 (2027)' and tu.nome in ('Turma 1', 'Turma 2');
  if v_turmas < 2 then
    raise warning 'Atividades do GitBook: achei % de 2 turmas da Edição 4 (2027); nada foi alterado', v_turmas;
    return;
  end if;

  delete from public.materiais m
  using atividades_do_gitbook v
  join public.trilhas t on t.nome = v.trilha
  where m.trilha_id = t.id and m.url = v.url and m.titulo = v.titulo and m.ordem = v.ordem;
  get diagnostics v_apagados = row_count;
  raise notice 'Atividades do GitBook: % links de atividade tirados da aba Materiais', v_apagados;

  select string_agg(distinct v.trilha, ', ') into v_faltando
  from atividades_do_gitbook v
  where not exists (select 1 from public.trilhas t where t.nome = v.trilha);
  if v_faltando is not null then
    raise warning 'Atividades do GitBook: trilhas não encontradas, ficaram sem atividades: %', v_faltando;
  end if;

  -- Na ordem do GitBook (turma, trilha, atividade): a tela desempata as sem prazo pelo id
  insert into public.atividades (turma_id, trilha_id, titulo, enunciado, link_enunciado, prazo)
  select tu.id, t.id, v.titulo, v.enunciado, v.url, null
  from atividades_do_gitbook v
  join public.trilhas t on t.nome = v.trilha
  cross join public.turmas tu
  join public.edicoes e on e.id = tu.edicao_id
  where e.nome = 'Edição 4 (2027)' and tu.nome in ('Turma 1', 'Turma 2')
    and not exists (
      select 1 from public.atividades a where a.turma_id = tu.id and a.link_enunciado = v.url
    )
  order by tu.id, t.ordem, v.ordem;
  get diagnostics v_criadas = row_count;
  raise notice 'Atividades do GitBook: % atividades criadas na Edição 4 (2027)', v_criadas;
end $$;

drop table atividades_do_gitbook;
